LocalGourmet/LocalGourmet.PL/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LocalGourmet.BLL.Models;
using LocalGourmet.BLL.Repositories;
using LocalGourmet.BLL.Services;
using LocalGourmet.PL.ViewModels;
using NLog;

namespace LocalGourmet.PL.Controllers
{
    public class RestaurantsController : Controller
    {
        private Logger log;
        private RestaurantRepository restaurantRepository;
        private ReviewRepository reviewRepository;

        public RestaurantsController()
        {
            log = LogManager.GetLogger("file");
            restaurantRepository = new RestaurantRepository();
            reviewRepository = new ReviewRepository();
        }

        public RestaurantsController(RestaurantRepository newRestaurantRepository,
            ReviewRepository newReviewRepository)
        {
            log = LogManager.GetLogger("file");
            restaurantRepository = newRestaurantRepository;
            reviewRepository = newReviewRepository;
        }

        // GET: Restaurants 
        public ActionResult Index(string sort)
        {
            IEnumerable<Restaurant> restaurants = restaurantRepository.GetAll();
            IEnumerable<Restaurant> tempRestaurants = restaurants.Reverse(); // Most recently created first
            try
            {
                if(sort == "byName")
                {
                    tempRestaurants = RestaurantService.SortByNameAsc(restaurants);
                }
                else if(sort == "byRating")
                {
                    tempRestaurants = RestaurantService.SortByAvgRatingDesc(restaurants);
                }
                else if(sort == "byCuisine")
                {
                    tempRestaurants = RestaurantService.SortByCuisineAsc(restaurants);
                }
                else if(sort == "topThree")
                {
                    tempRestaurants = RestaurantService.GetTop3(restaurants);
                }
                else if(sort != null)
                {
                    string search = sort; // "sort" var will store search info
                    tempRestaurants = RestaurantService.SearchByName(restaurants, search);
                }
                return View(tempRestaurants);
            }
            catch(Exception e)
            {
                log.Error($"[Restaurants Controller] [Index] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // GET: Restaurants/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                if(restaurantRepository.GetByID(id) == null)
                { throw new ArgumentNullException(); }
                RestaurantDetailsVM vm = new RestaurantDetailsVM(restaurantRepository, reviewRepository, id);
                return View(vm);
            }
            catch(Exception e)
            {
                log.Error($"[Restaurants Controller] [Details] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // GET: Restaurants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurants/Create
        [HttpPost]
        public ActionResult Create(BLL.Models.Restaurant restaurant)
        {
            try
            {
                if(ModelState.IsValid) // server-side validation
                {
                    restaurant.Active = true;
                    restaurantRepository.Add(restaurant);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(ModelState);
                }
            }
            catch(Exception e)
            {
                log.Error($"[Restaurants Controller] [Create] Exception thrown: {e.Message}");
                return View();
            }
        }

        // GET: Restaurants/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                Restaurant r = restaurantRepository.GetByID(id);
                if(r == null) { throw new ArgumentNullException("id"); }
                return View(r);
            }
            catch(Exception e)
            {
                log.Error($"[Restaurants Controller] [Edit] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // POST: Restaurants/Edit/5
        [HttpPost]
        public ActionResult Edit(Restaurant restaurant)
        {
            try
            {
                if(ModelState.IsValid) // server-side validation
                {
                    restaurantRepository.Update(restaurant);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(ModelState);
                }
            }
            catch(Exception e)
            {
                log.Error($"[Restaurants Controller] [Edit] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // GET: Restaurants/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Restaurant r = restaurantRepository.GetByID(id);
                if (r == null) { throw new ArgumentNullException("id"); }
                return View(r);
            }
            catch (Exception e)
            {
                log.Error($"[Restaurants Controller] [Delete] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // DELETE: Restaurants/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Restaurant r = restaurantRepository.GetByID(id);
                if (r == null) { throw new ArgumentNullException("id"); }
                restaurantRepository.Delete(r);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                log.Error($"[Restaurants Controller] [Delete] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }
    }
}

LocalGourmet/LocalGourmet.PL/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using LocalGourmet.BLL.Models;
using LocalGourmet.PL.ViewModels;
using NLog;
using LocalGourmet.BLL.Repositories;
using LocalGourmet.BLL.Services;

namespace LocalGourmet.PL.Controllers
{
    public class ReviewsController : Controller
    {
        private Logger log;
        private RestaurantRepository restaurantRepository;
        private ReviewRepository reviewRepository;

        public ReviewsController()
        {
            log = LogManager.GetLogger("file");
            reviewRepository = new ReviewRepository();
            restaurantRepository = new RestaurantRepository();
        }

        public ReviewsController(RestaurantRepository newRestaurantRepository,
            ReviewRepository newReviewRepository)
        {
            log = LogManager.GetLogger("file");
            restaurantRepository = newRestaurantRepository;
            reviewRepository = newReviewRepository;
        }

        // GET: Reviews
        public ActionResult Index(string sort)
        {
            try
            {
                var rrViewModel = new ReviewsIndexVM(reviewRepository, restaurantRepository);
                if(sort=="byRevName")
                {
                    rrViewModel.Reviews = ReviewService.SortByReviewerNameAsc(rrViewModel.Reviews);
                } else if(sort=="byRating")
                {
                    rrViewModel.Reviews = ReviewService.SortByOverallRatingDesc(rrViewModel.Reviews);
                } else if (sort=="byComment")
                {
                    rrViewModel.Reviews = ReviewService.SortByCommentAsc(rrViewModel.Reviews);
                }

                return View(rrViewModel);
            }
            catch(Exception e)
            {
                log.Error($"[Reviews Controller] [Index] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                Review r = reviewRepository.GetById(id);
                if (r == null) { throw new ArgumentNullException("id"); }
                return View(r);
            }
            catch(Exception e)
            {
                log.Error($"[Reviews Controller] [Details] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // GET: Reviews/Create
        public ActionResult Create(int? ID)
        {
            try
            {
                ReviewsCreateVM vm;
                if (ID == null)
                {
                    vm = new ReviewsCreateVM(restaurantRepository);
                }
                else
                {
                    vm = new ReviewsCreateVM((int) ID, restaurantRepository);
                }
                return View(vm);
            }
            catch (Exception e)
            {
                log.Error($"[Reviews Controller] [Create] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // POST: Reviews/Create
        [HttpPost]
        public ActionResult Create(ReviewsCreateVM vm)
        {
            try
            {
                if(ModelState.IsValid) // server-side validation
                {
                    reviewRepository.Add(vm.Review);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(ModelState);
                }
            }
            catch (Exception e)
            {
                log.Error($"[Reviews Controller] [Create] Exception thrown: {e.Message}");
                return View();
            }
        }

        // GET: Reviews/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                ReviewsEditVM vm = new ReviewsEditVM(id, reviewRepository, restaurantRepository);
                if (vm.Review == null) { throw new ArgumentNullException("id"); }
                return View(vm);
            }
            catch (Exception e)
            {
                log.Error($"[Reviews Controller] [Edit] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // POST: Reviews/Edit/5
        [HttpPost]
        public ActionResult Edit(Review review)
        {
            try
            {
                //ReviewsEditVM vm = new ReviewsEditVM(id, RestaurantID);
                if(ModelState.IsValid) // server-side validation
                {
                    reviewRepository.Update(review);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(ModelState);
                }
            }
            catch (Exception e)
            {
                log.Error($"[Reviews Controller] [Edit] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // GET: Reviews/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Review r = reviewRepository.GetById(id);
                if (r == null) { throw new ArgumentNullException("id"); }
                return View(r);
            }
            catch (Exception e)
            {
                log.Error($"[Reviews Controller] [Delete] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }

        // POST: Reviews/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Review r = reviewRepository.GetById(id);
                if (r == null) { throw new ArgumentNullException("id"); }
                reviewRepository.Delete(r);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                log.Error($"[Reviews Controller] [Delete] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }
    }
}

LocalGourmet/LocalGourmet.PL/Views/Restaurants/Create.cshtml
@model LocalGourmet.BLL.Models.Restaurant

@{
    ViewBag.Title = "Add Restaurant";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h1>New Restaurant</h1>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Cuisine, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cuisine, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cuisine, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Specialty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Specialty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Specialty, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <label class="control-label col-md-2">Phone Number</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <label class="control-label col-md-2">Web Address</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.WebAddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WebAddress, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Hours, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hours, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hours, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group" style="float:right; margin-right: 5px;">
                <input type="submit" value="Create" class="btn btn-default btn-toolbar" />
                <a href=@($"/Restaurants/Index") class="btn btn-default btn-toolbar">Back to List</a>
            </div>
            <br />
            <br />
        </div>
    }
    
</body>
</html>

LocalGourmet/LocalGourmet.PL/Views/Restaurants/Delete.cshtml
@model LocalGourmet.BLL.Models.Restaurant

@{
    ViewBag.Title = "Delete Restaurant";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this restaurant?</h3>
    <hr />
    <div>
        <dl class="dl-horizontal">
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Location)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Location)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Cuisine)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Cuisine)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Specialty)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Specialty)
            </dd>
    
            <dt>
                Phone Number
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
    
            <dt>
                Web Address
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.WebAddress)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Hours)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Hours)
            </dd>

            <dt>
                Number of Reviews
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Reviews.Count)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color" style="float:right;">
                <input type="submit" value="Delete" class="btn btn-default btn-toolbar" />
                <a href=@($"/Restaurants/Index") class="btn btn-default btn-toolbar">Back to List</a>
            </div>
            <br />
            <br />
        }
    </div>
</body>
</html>

LocalGourmet/LocalGourmet.PL/Views/Restaurants/Details.cshtml
@model LocalGourmet.PL.ViewModels.RestaurantDetailsVM

@{
    ViewBag.Title = Model.Restaurant.Name;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h1>
                @Html.DisplayFor(model => model.Restaurant.Name)
        </h1>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Restaurant.Location)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Restaurant.Location)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Restaurant.Cuisine)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Restaurant.Cuisine)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Restaurant.Specialty)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Restaurant.Specialty)
            </dd>

            <dt>
                Phone Number
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Restaurant.PhoneNumber)
            </dd>

            <dt>
                Web Address
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Restaurant.WebAddress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Restaurant.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Restaurant.Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Restaurant.Hours)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Restaurant.Hours)
            </dd>

            <dt>
                Number of Reviews
            </dt>

            <dd>
                @Model.Restaurant.Reviews.Count
            </dd>

            <dt>
                Average Rating
            </dt>

            <dd>
                @Model.Restaurant.GetAvgRating()
            </dd>

        </dl>
    </div>

    <div style="float:right;">
        <a href=@($"/Reviews/Create/{Model.Restaurant.ID}") class="btn btn-default btn-toolbar">Add Review</a>
        <a href=@($"/Restaurants/Edit/{Model.Restaurant.ID}") class="btn btn-default btn-toolbar">Edit</a>
        <a href=@($"/Restaurants/Delete/{Model.Restaurant.ID}") class="btn btn-default btn-toolbar">Delete</a>
        <a href=@($"/Restaurants/Index") class="btn btn-default btn-toolbar">Back to List</a>
    </div>
    <br />
    <br />
    
    @*Table of reviews for the restaurant*@
    <table class="table">
        <tr>
            <th>
                Reviewer Name
            </th>
            <th>
                Comment
            </th>
            <th>
                Overall Rating (0-5)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Reviews)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ReviewerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @item.GetRating()
            </td>
            <td>
                <div style="min-width: 200px;">
                    <a href=@($"/Reviews/Details/{item.ID}") class="btn btn-default btn-toolbar">Details</a>
                    <a href=@($"/Reviews/Edit/{item.ID}") class="btn btn-default btn-toolbar">Edit</a>
                    <a href=@($"/Reviews/Delete/{item.ID}") class="btn btn-default btn-toolbar">Delete</a>
                </div>
            </td>
        </tr>
        }
    </table>

    <br />
    <hr />
    <div style="float:right;">
        <a href=@($"/Reviews/Create/{Model.Restaurant.ID}") class="btn btn-default btn-toolbar">Add Review</a>
        <a href=@($"/Restaurants/Edit/{Model.Restaurant.ID}") class="btn btn-default btn-toolbar">Edit</a>
        <a href=@($"/Restaurants/Delete/{Model.Restaurant.ID}") class="btn btn-default btn-toolbar">Delete</a>
        <a href=@($"/Restaurants/Index") class="btn btn-default btn-toolbar">Back to List</a>
    </div>
    <br />
    <br />
</body>
</html>

LocalGourmet/LocalGourmet.PL/Views/Restaurants/Index.cshtml
@model IEnumerable<LocalGourmet.BLL.Models.Restaurant>

@{
    ViewBag.Title = "Restaurants";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script>
        function SearchByName() {
            $.ajax({
                method: "GET",
                url: "Restaurants/Index/",
                data: { sort: document.getElementsByName("sort")[0].value }
            })
        }
    </script>
</head>
<body>
    <h1>Restaurants</h1>
    <hr />
    <div>
        <span>@Html.ActionLink("Add new Restaurant", "Create", "Restaurants", null, new { @class = "btn btn-default btn-toolbar" })</span>
        <span>@Html.ActionLink("Sort by Name", "Index", "Restaurants", new { sort = "byName" }, new { @class = "btn btn-default btn-toolbar" })</span>
        <span>@Html.ActionLink("Sort by Rating", "Index", "Restaurants", new { sort = "byRating" }, new { @class = "btn btn-default btn-toolbar" })</span>
        <span>@Html.ActionLink("Sort by Cuisine", "Index", "Restaurants", new { sort = "byCuisine" }, new { @class = "btn btn-default btn-toolbar" })</span>
        <span>@Html.ActionLink("Top Three", "Index", "Restaurants", new { sort = "topThree" }, new { @class = "btn btn-default btn-toolbar" })</span>
        
        <form id="searchForm" onsubmit="SearchByName()" style="display:inline;">
            <input type="submit" value="Search by Name" class="btn btn-default btn-toolbar">
            <input type="text" name="sort" placeholder="keywords...">
        </form>
    </div>
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuisine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th style="width:100px;">
                Number of Reviews
            </th>
            <th>
                Average Rating
            </th>
            <th></th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuisine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reviews.Count)
            </td>
            <td>
                @item.GetAvgRating()
            </td>
            <td> 
                <div style="min-width:210px">
                    <span>@Html.ActionLink("Create", "Create", "Reviews", item.ID, new { @class = "btn btn-default btn-toolbar" })</span>
                    <span>@Html.ActionLink("Details", "Details", "Reviews", item.ID, new { @class = "btn btn-default btn-toolbar" })</span>
                    <span>@Html.ActionLink("Edit", "Edit", "Reviews", item.ID, new { @class = "btn btn-default btn-toolbar" })</span>
                    <span>@Html.ActionLink("Delete", "Delete", "Reviews", item.ID, new { @class = "btn btn-default btn-toolbar" })</span>
                    @*<a style="margin-bottom: 3px; width:100px;" href=@($"/Reviews/Create/{item.ID}") class="btn btn-default btn-toolbar">Add Review</a>
                    <a style="margin-bottom: 3px; width:100px;" href=@($"/Restaurants/Details/{item.ID}") class="btn btn-default btn-toolbar">Details</a>
                    <a style="margin-bottom: 3px; width:100px;"  href=@($"/Restaurants/Edit/{item.ID}") class="btn btn-default btn-toolbar">Edit</a>
                    <a style="margin-bottom: 3px; width:100px;" href=@($"/Restaurants/Delete/{item.ID}") class="btn btn-default btn-toolbar">Delete</a>*@
                </div>
            </td>
        </tr>
    }
    
    </table>
</body>
</html>